add_rules("mode.debug","mode.release")
add_defines("WIN32",{public=true})
--add_requires("eigen >=3.4.0")
add_requires("fmt >=8.1.1")
add_requires("nlohmann_json >=3.10.5")
target("simplex_common")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu")
    add_includedirs(".",{public=true})
    add_includedirs("./../../simplex/ext/eigen",{public=true})
    add_packages("eigen",{public=true})
    add_packages("fmt",{public=true})
    add_packages("nlohmann_json",{public=true})
    add_cugencodes("native")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_cuflags("-Xcompiler /openmp")
