add_rules("mode.debug","mode.release")
set_languages("cxx17")
includes("./../simplex_physics/xmake.lua")
add_defines("WIN32")
includes("./../../meso/src/particle_algorithm/xmake.lua")
includes("./../../meso/src/grid_algorithm/xmake.lua")
--add_requires("vtk >=9.1.0")
add_requires("mma >=2018.08.01")
--add_requires("amgcl >=1.4.2")
target("topo-voronoi")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_cuflags("-Xcompiler /openmp")
    --add_packages("vtk",{public=true})
    add_packages("mma",{public=true})
    --add_packages("amgcl",{public=true})
    add_deps("simplex_physics")
    add_deps("particle_algorithm")
    add_deps("grid_algorithm")
    