add_rules("mode.debug","mode.release")
includes("./../../meso/src/particle_algorithm/xmake.lua")
includes("./../../meso/src/mesh_algorithm/xmake.lua")
add_requires("vtk >=9.1.0")
add_requires("mma >=2018.08.01")
target("topo-voronoi")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native")
    add_cugencodes("compute_61")
    add_cuflags("--extended-lambda")
    add_cuflags("-Xcompiler /openmp")
    add_packages("vtk",{public=true})
    add_packages("mma",{public=true})
    add_deps("particle_algorithm")
    add_deps("mesh_algorithm")
