add_rules("mode.debug","mode.release")
includes("./../simplex_common/xmake.lua")
target("simplex_reservoir")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("static")
    add_headerfiles("./../../simplex/src/reservoir/*.h")
    add_files("./../../simplex/src/reservoir/*.cpp","./../../simplex/src/reservoir/*.cu")
    add_includedirs("./../../simplex/src/reservoir",{public=true})
    add_cugencodes("native")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_cuflags("-Xcompiler /openmp")
    add_deps("simplex_common")
