add_rules("mode.debug","mode.release")
includes("./../simplex_reservoir/xmake.lua")
--includes("./../../meso/src/solver/xmake.lua")
add_requires("cuda", {system=true, configs={utils={"cublas","cusparse","cusolver"}}})
add_requires("amgcl >=1.4.2")
target("simplex_solver")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu")
    add_includedirs(".",{public=true})
    add_cugencodes("native")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_cuflags("-Xcompiler /openmp")
    add_packages("cuda",{public=true})
    add_packages("amgcl",{public=true})
    add_deps("simplex_reservoir")
    --add_deps("solver")
