add_rules("mode.debug","mode.release")
includes("./../simplex_geometry/xmake.lua")
includes("./../simplex_parallel/xmake.lua")
target("simplex_physics")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu")
    add_includedirs(".",{public=true})
    add_cugencodes("native")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_cuflags("-Xcompiler /openmp")
    add_deps("simplex_geometry")
    add_deps("simplex_parallel")
