add_rules("mode.debug","mode.release")
includes("./../simplex_reservoir/xmake.lua")
--add_requires("nanoflann =1.4.2")
target("simplex_geometry")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu")
    add_includedirs(".",{public=true})
    --add_packages("nanoflann",{public=true})
    add_cugencodes("native")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_cuflags("-Xcompiler /openmp")
    add_deps("simplex_reservoir")
